### ISSUE TITLE
charcoal `TypeError` in rule `make_contigs_taxonomy_json` with abundance signature

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/charcoal#177]
sourmash version 4.1.1
```
$ python -m charcoal run genbank_genomes.conf --rerun-incomplete
** read 361 provided lineages
** config file checks PASSED!
** from here on out, it's all snakemake...
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       combine_genome_summary
        1       combine_hit_list
        1       compare_taxonomy_single
        1       make_contigs_taxonomy_json
        1       make_index
        1       set_kernel
        7

[Tue May 25 10:11:48 2021]
rule make_contigs_taxonomy_json:
    input: /home/tereiter/github/2020-ibd/genbank_genomes/GCA_000210075.1_genomic.fna.gz, output.genbank_genomes/stage1/GCA_000210075.1_genomic.fna.gz.sig, output.genbank_genomes/stage1/GCA_000210075.1_genomic.fna.gz.matches.zip, /group/ctbrowngrp/gtdb/gtdb-rs202.taxonomy.csv
    output: output.genbank_genomes/stage1/GCA_000210075.1_genomic.fna.gz.contigs-tax.json
    jobid: 4
    wildcards: f=GCA_000210075.1_genomic.fna.gz

Activating conda environment: /home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9
examining spreadsheet headers...
** assuming column 'ident' is identifiers in spreadsheet
loaded 258406 tax assignments.
loaded 1774 matches from 'output.genbank_genomes/stage1/GCA_000210075.1_genomic.fna.gz.matches.zip'
removing an identical match: GCA_000210075.1 Bacteroides xylanisolvens XB1A strain=XB1A, ASM21007v1
loaded 1773 signatures & created LCA Database

reading contigs from GCA_000210075.1_genomic.fna.gz
Traceback (most recent call last):
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tereiter/github/charcoal/charcoal/contigs_search_taxonomy.py", line 127, in <module>
    returncode = cmdline(sys.argv[1:])
  File "/home/tereiter/github/charcoal/charcoal/contigs_search_taxonomy.py", line 122, in cmdline
    return main(args)
  File "/home/tereiter/github/charcoal/charcoal/contigs_search_taxonomy.py", line 92, in main
    results = list(gather_at_rank(mh, lca_db, lin_db, match_rank))
  File "/home/tereiter/github/charcoal/charcoal/utils.py", line 156, in gather_at_rank
    results = lca_db.gather(query_sig, threshold_bp=0)
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/site-packages/sourmash/index.py", line 214, in gather
    for result in self.prefetch(query, threshold_bp, **kwargs):
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/site-packages/sourmash/index.py", line 207, in prefetch
    for sr in self.find(search_fn, query, **kwargs):
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/site-packages/sourmash/lca/lca_db.py", line 434, in find
    search_fn.check_is_compatible(query)
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/site-packages/sourmash/search.py", line 116, in check_is_compatible
    raise TypeError("this search cannot be done with an abund signature")
TypeError: this search cannot be done with an abund signature
[Tue May 25 10:12:11 2021]
Error in rule make_contigs_taxonomy_json:
    jobid: 4
    output: output.genbank_genomes/stage1/GCA_000210075.1_genomic.fna.gz.contigs-tax.json
    conda-env: /home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9
    shell:

        python -m charcoal.contigs_search_taxonomy             --genome /home/tereiter/github/2020-ibd/genbank_genomes/GCA_000210075.1_genomic.fna.gz --lineages-csv /group/ctbrowngrp/gtdb/gtdb-rs202.taxonomy.csv             --genome-sig output.genbank_genomes/stage1/GCA_000210075.1_genomic.fna.gz.sig             --matches-sig output.genbank_genomes/stage1/GCA_000210075.1_genomic.fna.gz.matches.zip             --json-out output.genbank_genomes/stage1/GCA_000210075.1_genomic.fna.gz.contigs-tax.json             --match-rank order

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/tereiter/github/charcoal/.snakemake/log/2021-05-25T101147.655726.snakemake.log
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/charcoal/charcoal/Snakefile', '--use-conda', '-j', '1', '--rerun-incomplete', '--configfile', '/home/tereiter/github/charcoal/charcoal/conf/defaults.conf', '/home/tereiter/github/charcoal/charcoal/conf/system.conf', 'genbank_genomes.conf']' returned non-zero exit status 1.
```

**Comment by ctb** [comment]
right, use minhash.flatten() in there.
