### ISSUE TITLE
charcoal target `clean` does not work

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/charcoal#185]
On branch latest, but with `update/deps` updated in my `(charcoal)` environment.

```
$ python -m charcoal run genbank_genomes.conf -j 16 clean
** read 361 provided lineages
** config file checks PASSED!
** from here on out, it's all snakemake...
Building DAG of jobs...
MissingRuleException:
No rule to produce clean (if you use input functions make sure that they don't raise unexpected exceptions).
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/charcoal/charcoal/Snakefile', '--use-conda', '-j', '1', '-j', '16', 'clean', '--configfile', '/home/tereiter/github/charcoal/charcoal/conf/defaults.conf', '/home/tereiter/github/charcoal/charcoal/conf/system.conf', 'genbank_genomes.conf']' returned non-zero exit status 1.
```
Trying with `--until`
```
$ python -m charcoal run genbank_genomes.conf -j 16 --until clean_contigs

** read 361 provided lineages
** config file checks PASSED!
** from here on out, it's all snakemake...
Building DAG of jobs...
Updating job make_index.
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/charcoal/lib/python3.9/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/home/tereiter/miniconda3/envs/charcoal/lib/python3.9/site-packages/snakemake/workflow.py", line 731, in execute
    dag.update_checkpoint_dependencies()
  File "/home/tereiter/miniconda3/envs/charcoal/lib/python3.9/site-packages/snakemake/dag.py", line 1312, in update_checkpoint_dependencies
    self.postprocess()
  File "/home/tereiter/miniconda3/envs/charcoal/lib/python3.9/site-packages/snakemake/dag.py", line 1193, in postprocess
    self.cleanup()
  File "/home/tereiter/miniconda3/envs/charcoal/lib/python3.9/site-packages/snakemake/dag.py", line 258, in cleanup
    del self.depending[dep][job]
KeyError: prefetch_all
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/charcoal/charcoal/Snakefile', '--use-conda', '-j', '1', '-j', '16', '--until', 'clean_contigs', '--configfile', '/home/tereiter/github/charcoal/charcoal/conf/defaults.conf', '/home/tereiter/github/charcoal/charcoal/conf/system.conf', 'genbank_genomes.conf']' returned non-zero exit status 1.
```

**Comment by taylorreiter** [comment]
Think I got it:

```
python -m charcoal run genbank_genomes.conf -j 16 all_clean_contigs
```
