### ISSUE TITLE
KeyError in charcoal target `all_clean_contigs`

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/charcoal#186]
```
$ python -m charcoal run genbank_genomes.conf -j 1 all_clean_contigs
** read 361 provided lineages
** config file checks PASSED!
** from here on out, it's all snakemake...
Building DAG of jobs...
Updating job clean_contigs.
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all_clean_contigs
        122     clean_contigs
        123
Select jobs to execute...

[Wed Jun  2 16:56:30 2021]
rule clean_contigs:
    input: /home/tereiter/github/2020-ibd/genbank_genomes/GCF_005845265.1_genomic.fna.gz, output.genbank_genomes/stage1/GCF_005845265.1_genomic.fna.gz.contigs-tax.json, output.genbank_genomes/stage1_hitlist.csv
    output: output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.clean.fa.gz, output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.dirty.fa.gz
    jobid: 1663
    wildcards: f=GCF_005845265.1_genomic.fna.gz

Activating conda environment: /home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9
loaded 58 contig assignments.
filtering GCF_005845265.1_genomic.fna.gz contigs at order
note, genome lineage is d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales
Traceback (most recent call last):
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tereiter/github/charcoal/charcoal/clean_genome.py", line 134, in <module>
    returncode = cmdline(sys.argv[1:])
  File "/home/tereiter/github/charcoal/charcoal/clean_genome.py", line 129, in cmdline
    return main(args)
  File "/home/tereiter/github/charcoal/charcoal/clean_genome.py", line 98, in main
    gather_info = contigs_d[record.name]
KeyError: 'NZ_SPHP01000055.1 Clostridium sp. 1001175st1 A10 strain 1001175st1_A10 NODE_55_length_2677_cov_60.1085, whole genome shotgun sequence'
[Wed Jun  2 16:56:36 2021]
Error in rule clean_contigs:
    jobid: 1663
    output: output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.clean.fa.gz, output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.dirty.fa.gz
    conda-env: /home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9
    shell:

        python -m charcoal.clean_genome             --genome /home/tereiter/github/2020-ibd/genbank_genomes/GCF_005845265.1_genomic.fna.gz             --hit-list output.genbank_genomes/stage1_hitlist.csv             --contigs-json output.genbank_genomes/stage1/GCF_005845265.1_genomic.fna.gz.contigs-tax.json             --clean output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.clean.fa.gz --dirty output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.dirty.fa.gz

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job clean_contigs since they might be corrupted:
output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.clean.fa.gz, output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.dirty.fa.gz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/tereiter/github/charcoal/.snakemake/log/2021-06-02T165625.652902.snakemake.log
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/charcoal/charcoal/Snakefile', '--use-conda', '-j', '1', '-j', '1', 'all_clean_contigs', '--configfile', '/home/tereiter/github/charcoal/charcoal/conf/defaults.conf', '/home/tereiter/github/charcoal/charcoal/conf/system.conf', 'genbank_genomes.conf']' returned non-zero exit status 1.
```

The offending line in `charcoal/clean_genome.py` has a comment indicating that this is an error stemming from an issue with the hitlist
```
for record in screed_iter:
        # note: if record.name is not in the contigs dictionary, that
        # means that the code that output the hitlist did something
        # wrong!
        gather_info = contigs_d[record.name]
```

The offending node listed above does not appear in `GCF_005845265.1_genomic.fna.gz.contigs-tax.json`

This error happened 122 times on 361 genomes that I ran it on...I'm not really sure where it's coming from yet

**Comment by taylorreiter** [comment]
Assembly accession GCF_005845265.1 is:
+ *Clostridium sp. 1001175st1 A10* in the NCBI taxonomy
+ *d__Bacteria; p__Firmicutes_A; c__Clostridia; o__Lachnospirales; f__Lachnospiraceae; g__Hungatella; s__Hungatella sp005845265* in the GTDB taxonomy
+ a GTDB representative species

The key error is for `NZ_SPHP01000055.1 Clostridium sp. 1001175st1 A10 strain 1001175st1_A10 NODE_55_length_2677_cov_60.1085`

The script `charcoal/contigs_search_taxonomy.py` outputs the json file that becomes `contigs_d` that does not contain the node that's causing the KeyError.

...but I can't see an obvious reason that some contigs wouldn't make it in to the json file.

**Comment by ctb** [comment]
hi taylor, could you put together a short/simple reproducible example? Should be do-able by just isolating one or two of these genomes for a new config file. thanks!

**Comment by ctb** [comment]
as a side note,
```
python -m charcoal run demo/demo.conf all_clean_contigs
```
runs without error.

**Comment by taylorreiter** [comment]
I think the attached config file will run anywhere on farm, but I'm also including the requisite files here
Conf file: [genbank_genomes_tiny3.conf.txt](https://github.com/dib-lab/charcoal/files/6593022/genbank_genomes_tiny3.conf.txt)
Genome list: [genbank_genomes_tiny2.genome-list.txt](https://github.com/dib-lab/charcoal/files/6593040/genbank_genomes_tiny2.genome-list.txt)
Genome: [GCF_005845265.1_genomic.fna.gz](https://github.com/dib-lab/charcoal/files/6593024/GCF_005845265.1_genomic.fna.gz)
Database: (too big to upload here...can put on osf if necessary)
Lineages: [lineages.csv](https://github.com/dib-lab/charcoal/files/6593034/lineages.csv)




The only file not included in this tar is the db lineages, which can be downloaded from osf here: https://osf.io/p6z3w/

**Comment by ctb** [comment]
I can reproduce this error on farm - thanks! May take me some time to figure it out tho :)
